config/routes.rb
Rails.application.routes.draw do
  
  resources :posts
  resources :projects
  get 'welcome/index'

  root 'welcome#index'



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord

     extend FriendlyId
     friendly_id :title, use: :slugged
  
end

app/models/project.rb
class Project < ApplicationRecord

    extend FriendlyId
    friendly_id :title, use: :slugged

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

    before_action :find_post, only: [:show, :edit, :update, :destroy]

    def index
        @post = Post.all.order("created_at desc").paginate(page: params[:page], per_page: 5)
    end

    def new
        @post = Post.new
    end

    def create
        @post = Post.new post_params

        if @post.save
            redirect_to @post, notice: "Hello,its done!"
        else
            render 'new', notice: "Oh no,not done"
        end
    end

    def show
       
    end

    def edit
    end

    def update
        if @post.update post_params
            redirect_to @post, notice: "updated successfuly!"
        else
            render 'edit'
        end

    end

    def destroy
    
        @post.destroy
        redirect_to posts_path
    
    end



    private

    def post_params
        params.require(:post).permit(:title, :content, :slug)
    end

    def find_post
         @post = Post.friendly.find(params[:id])
    end




end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
    before_action :find_project, only: [:show, :edit, :update, :destroy]
    
    def index
        @projects = Project.all.order("created_at desc")
    end

    def new
        @project = Project.new
    end

    def create
        @project = Project.new project_params

        if @project.save
            redirect_to @project, notice: "Nice, Your project is saved!"
        else
            render 'new'
        end
    end

    def show
    end


    def edit
    end

    def update
        if @project.update project_params
            redirect_to @project, notice: "Nice, you have successfully"
        else
            render 'edit'
        end
    end

    def destroy
        @project.destroy
        redirect_to projects_path
    end


    private

    def find_project
        @project = Project.friendly.find(params[:id])
    end

    def project_params
        params.require(:project).permit(:title, :description, :link)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

    def index
        @posts = Post.all.limit(3).order("created_at desc")
        @projects = Project.all.limit(3).order("created_at desc")
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    class HTMLwithPygments < Redcarpet::Render::HTML
        def block_code(code, language)
            Pygments.highlight(code, lexer: language)
        end
    end
    def markdown(content)
        renderer = HTMLwithPygments.new(hard_wrap: true, filter_html: true,fenced_code_blocks: true)
        options = {
            autolink: true,
            no_intra_emphasis: true,
            fenced_code_blocks: true,
            lax_html_blocks: true,
            strikethrough: true,
            superscript: true
        }

        Redcarpet::Markdown.new(renderer, options).render(content).html_safe
        
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shubham Shukla,Designer Developer</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU"
        crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Raleway:400,700" rel="stylesheet">
  
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <header id="main_navigation" class="clearfix">
        
        <%= link_to "shubh_spcl", root_path, class: "name" %>
        
        <nav>
            <%= link_to "Articles", posts_path %>
            <%= link_to "Projects", projects_path %>
            
            <a href="#">Contact</a>
        </nav>

    </header>
    <%= yield %>

     <footer id="main_footer">
        <p class="copyright">&copy;2018 shubh_spcl</p>
        <nav>
            <a href="#"><i class="fa fa-twitter"></i></a>
            <a href="#"><i class="fa fa-facebook"></i></a>
            <a href="#"><i class="fa fa-github"></i></a>
        </nav>
    </footer>
  </body>
</html>

app/views/posts/_disqus.html.erb
<div id="disqus_thread"></div>
<script>


 
/**
*  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
*  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
/*
var disqus_config = function () {
 var disqus_shortname = 'shubh_spcl_blog';
  var disqus_identifier = '<%= @post.id %>';
  var disqus_title = '<%= @post.title %>';
  var disqus_url = '<%= url_for([@post, {only_path: false}]) %>';
};
*/
(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');
s.src = 'https://shubh-spcl-blog.disqus.com/embed.js';
s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
                            

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>

<% if @post.errors.any? %>

  <h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving:</h2>
  <ul>
  	<% @post.errors.full_messages.each do |msg| %>
   		<li><%= msg %></li>
   	<% end %>
  </ul>
  <% end %>

  <%= f.label :title %><br>
  <%= f.text_field :title %>

  <br>
  <br>

  <%= f.label :content, "Write your article here" %><br>

  <%= f.text_area :content %>

  <br>
  <br>

  <%= f.submit %>

<% end %>

app/views/posts/disqus.html.erb
<div id="disqus_thread"></div>
<script>

/**
*  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
*  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
/*
var disqus_config = function () {
this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
};
*/
(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');
s.src = 'https://shubh-spcl-blog.disqus.com/embed.js';
s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
                            

app/views/posts/edit.html.erb
<h1>I love tripti</h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<h1 id="page_title">Stuff I've Written</h1>

    <div id="posts_wrapper" class="skinny_wrapper">
    <% @post.each do |post| %>
        <div class="post">
            <p class="date"><%= post.created_at.strftime('%A, %B %d') %></p>
            <h2><a href="article_show.html"><%= link_to post.title, post %></a></h2>
            <hr>
        </div>

        <% end %>
     </div>
    

    <div class="pagination">
        <span class="previous_page disabled">Previous</span>
        <em class="current">1</em>
        <a href="#" rel="next" >2</a>
        <a href="#" class="next_page">Next</a>
    </div>

app/views/posts/new.html.erb
<h1>Dubstainment-- tripti</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<div id="post_show_content" class="skinny_wrapper wrapper_padding">
        <header>
            <p class="date"><%= @post.created_at.strftime('%A, %B %d') %></p>

            <h1><%= @post.title %></h1>
            <hr>
        </header>

        <div id="content">
            <%= markdown @post.content %>

        </div>

        <hr>

        <div id="share_box">
            <p>Share My First AMP</p>
            <a href="#"><i class="fab fa-twitter"></i></a>
            <a href="#"><i class="fab fa-facebook"></i></a>
            <a href="#"><i class="fab fa-google-plus"></i></a>
        </div><hr>
    </div>

    <hr>

    <%= render 'disqus' %>




<br>
<br>

<%= link_to "Edit", edit_post_path(@post) %>
<%= link_to "Delete", post_path(@post), method: :delete, data: { confirm: "Are you sure?"} %>

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>

<% if @project.errors.any? %>

  <h2><%= pluralize(@project.errors.count, "error") %> prevented this project from saving:</h2>
  <ul>
  	<% @project.errors.full_messages.each do |msg| %>
   		<li><%= msg %></li>
   	<% end %>
  </ul>
  <% end %>

  <%= f.label :title %><br>
  <%= f.text_field :title %>

  <br>
  <br>

  <%= f.label :description %><br>

  <%= f.text_area :description %>

  <br>
  <br>

  <%= f.label :link %><br>
  <%= f.text_field :link %>

  <br>
  <br>


  <%= f.submit %>

<% end %>

app/views/projects/edit.html.erb
<h1>Edit Project</h1>

<%= render 'form' %>

app/views/projects/index.html.erb
<h1 id="page_title">Stuff I have Built</h1>

    <div id="posts_wrapper" class="skinny_wrapper">
    <% @projects.each do |projects| %>
        <div class="post">
            <p class="date"><%= projects.created_at.strftime('%A, %B %d') %></p>
            <h2><a href=""><%= link_to projects.title, projects %></a></h2>
            <hr>
        </div>

        <% end %>
     </div>

app/views/projects/new.html.erb
<div class="skinny_wrapper wrapper_padding">

<h1>New Project</h1>

<%= render 'form' %>

</div>

app/views/projects/show.html.erb
<div id="post_show_content" class="skinny_wrapper wrapper_padding">
        <header>
            <p class="date"><%= @project.created_at.strftime('%A, %B %d') %></p>

            <h1><%= @project.title %></h1>
            <hr>
        </header>

        <div id="content">
            <%= markdown @project.description %>
            <div class="button_wrapper">
            <a href="<%= @project.link %>" class="project_button" target="_blank">Visit <%= @project.title %>
            </a>
            </div>

        </div>

        <%= link_to "Edit", edit_project_path(@project) %>
        <%= link_to "Delete", project_path(@project), method: :delete, data: { confirm: "Are you sure?"} %>
        <hr>
</div>

app/views/welcome/index.html.erb
<div class="wrapper wrapper_padding clearfix">
        <div class="col-1 homepage_content">
            <h2>About</h2>
            <hr>
            <p>I'm a Developer & Designer based in Noida,India</p>
           <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam ac mauris sed libero malesuada vestibulum id ac neque.</p>
           <p>aliquet quam quis, tempus nunc. Fusce aliquet eget justo et venenatis. Integer non justo a justo vehicula maximus.</p>
            <p>Suspendisse pulvinar mi vitae sem ultrices hendrerit.</p><p>Morbi sollicitudin consequat pharetra. Ut vehicula pharetra
            maximus. Nulla ut elit a leo mattis porta eu ut eros.</p>
        </div>
        <div class="col-2 homepage_content">
         <h2>Stuffs I have Written</h2>
         <hr>

         <% @posts.each do |post| %>

         <h3><a href="#"><%= link_to post.title, post %></a></h3>
         <p class="date"><%= post.created_at.strftime("%A, %b %d") %></p>
         <% end %>
       
        </div>

        <div class="col-3 homepage_content">
            <h2>Stuff I have Made</h2>
            <hr>
             <% @projects.each do |project| %>

            <h3><a href="#"><%= link_to project.title, project %></a></h3>
            <p class="date"><%= project.created_at.strftime("%A, %b %d") %></p>
            <% end %>
        
        </div>
        </div>
    </div>